version: '3'
services:
  elo:
    image: felixbreuer/elo-hell:latest
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./elo-db:/data/db
    ports:
      - 27017:27017
